[package]
name = "winftw"
version = "0.1.0"
authors = ["Raymai97 <cheeboonray@gmail.com>"]

[dependencies]
libc = "0.1.10"
user32-sys = "0.1.2"
kernel32-sys = "0.1.4"

[dependencies.winapi]
version = "0.2.8"
path = "C:/Users/Raymai/Desktop/winapi-rs"
